### ISSUE TITLE
Suggestion: Add blog post content to README

### ISSUE THREAD

**Issue by batpigandme** [jsugarelli/packagefinder#2]
Thought it'd be nice to have the contents of this post (at a minimum, at least) in your README;
https://topics-in-r.blogspot.com/2018/07/new-package-packagefinder.html.

It's a cool package, and I wouldn't want anyone to miss out by not having the nice little visuals!

**Comment by jsugarelli** [comment]
Excellent idea, thanks! Will be done in the next release.

**Comment by jsugarelli** [comment]
I have added a full tutorial (available in README file and on http://www.zuckarelli.de/packagefinder/tutorial.html).

**Comment by eabase** [comment]
:exclamation:  Attention: 
That blog post is broken because of changes in both `pf()` and `as.tibble()`.
