### ISSUE TITLE
Get a list of the found packages as an object in R

### ISSUE THREAD

**Issue by DrMattG** [jsugarelli/packagefinder#4]
Hi - this is probably a stupid question but how do I get a list of packages as an object in R? I would like to be able to use it like this:

`pkgs<-packagefinder::findPackage(keywords = "ecology")

pkgs$name

pkgs$score`

Is that possible? 

Thanks for a great package!

Matt

**Comment by jsugarelli** [comment]
Hi Matt,

simply use `return.df = TRUE` as an additional argument.

Best
Joachim

**Comment by eabase** [comment]
This is a pretty important change, which breaks a bunch of examples, elsewhere! E.g.
* https://rviews.rstudio.com/2018/10/22/searching-for-r-packages/

Without this I was not able to select on Column names! 

Please add this to your README.
